- Slider/Assets/Scenes/Dev/ab92/pro jungler.unity
- Slider/Assets/Scenes/Dev/ab92/pro jungler.unity.meta
- Slider/Assets/Scripts/Sliders/Grid/SGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/STile.cs
- Slider/Assets/Scripts/UI/Artifact/UIArtifact.cs
2x1 linked tile works correctly
Manual labor
> linked tile works correctly 2x1

- Slider/Assets/Scenes/Dev/Koushik.meta
- Slider/Assets/Scenes/Dev/Koushik/npc test.unity.meta
- Slider/Assets/Scripts/Utility/Control/Condition.cs
- Slider/Assets/Scripts/Utility/Control/Condition.cs.meta
- Slider/Assets/Scripts/Utility/Control/Conditionals.cs
Added Condition and Conditionals, which are useful for handling NPCs and other player progress gates.
Condition and Conditionals use UnityEvents to trigger certain functions based on if a set of conditions are met, namely a specific tile pattern, or a held collectible.
Conditionals
Smart Coding :)
Tested in Inspector
Separate from all other areas of code
> Condition and Conditionals

- .gitignore
- Slider/Assets/BootsSpeedIncrease.cs
- Slider/Assets/BootsSpeedIncrease.cs.meta
- Slider/Assets/Prefabs/Interactable/Collectibles/Boots.prefab
- Slider/Assets/Prefabs/Interactable/Collectibles/Boots.prefab.meta
- Slider/Assets/Scenes/Caves.unity
- Slider/Assets/Scripts/Player/Player.cs
speed boots implemented
- still awaiting sprite tho
- also not sure how persistent data / save data is handled in the game so i'm ignoring that for now lol (basically, if you restart the game, your speed resets, idk if the owners of the game want the speed data to "save" and "load" whenever you load up the game again)
https://trello.com/c/PlbiWDgu/41-boots-of-speed
I made a new scene, dragged that prefab in, and collected it. Also tested it with a higher speed, and speed does increment correctly so
too lazy
> speed boots implemented

- Slider/Assets/Prefabs/Map/Decoration/Caves/CaveRock1.prefab
- Slider/Assets/Prefabs/Map/Decoration/Caves/CaveRock2 Variant.prefab
- Slider/Assets/Prefabs/Map/Decoration/Caves/Tall Stalagmite1.prefab
- Slider/Assets/Prefabs/Map/Decoration/Caves/Tall Stalagmite4.prefab
- Slider/Assets/Scripts/Sliders/Grid/AreaSTiles/CaveSTile.cs
Updated the BlocksLight tag to work with objects.
Moss Lighting
Tested it by adding BlocksLight tags to the objects in the Moss puzzle and verifying that they blocked the lights from different directions.
> BlocksLight Patch

- Slider/Assets/Scenes/Dev/Travis.meta
- Slider/Assets/Scenes/Dev/Travis/Base Scene.unity
- Slider/Assets/Scenes/Dev/Travis/Base Scene.unity.meta
- Slider/Assets/Scripts/UI/UIEffects.cs
Update UIEffects to store the previously run coroutine for fading to/from black and flashing white and end it when a new one is started.
Fade to black when you go too fast
Loaded Village scene and walked in and out of the house quickly. Observed that everything worked as expected.
> Make Calling Fade/Flash Methods Stop Coroutines

- Slider/Assets/Scripts/Steamworks.NET.meta
- Slider/Assets/Scripts/Steamworks.NET/SteamCheck.cs
- Slider/Assets/Scripts/Steamworks.NET/SteamCheck.cs.meta
- Slider/Assets/Scripts/Steamworks.NET/SteamManager.cs
- Slider/Assets/Scripts/Steamworks.NET/SteamManager.cs.meta
- Slider/ProjectSettings/ProjectSettings.asset
refix steam
build target isnt tracked by git so i was targetting web the whole time
> basically undo my changes :|

- Slider/Assets/Scripts/Map/Cave/CaveLight.cs
- Slider/Assets/Scripts/Map/Cave/CaveMossManager.cs
- Slider/Assets/Scripts/Map/Cave/PoweredLight.cs
- Slider/Assets/Scripts/NPCs/NPC.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/CaveGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/VillageGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/SGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/SGridAnimator.cs
> Caves Puzzles

- Slider/Assets/Scenes/Ocean.unity.meta
Updated the actual ocean scene (fixed fisherman dialog).
> Ocean Actually Updated

- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/CaveGrid.cs
> Scuffy M2 Fix I think. Idk. Game still broken. :meownotlikethis:

- Slider/Assets/Scenes/Dev/Kris/Ocean 1.unity.meta
- Slider/Assets/Scenes/Ocean.unity.meta
- Slider/Assets/Scripts/Audio/AudioManager.cs
- Slider/Assets/Scripts/Map/Puzzles/LostGuyMovement.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/OceanGrid.cs
- Slider/Assets/Sprites/Items/jungle_items.png.meta
Finished Impletementing Foggy Puzzle and fixed bugs.
> Ocean Scene Complete

- Slider/Assets/Scripts/Discord/DiscordController.cs
Use try-catch to make Discord SDK shut up when Discord isn't open
> Make Discord Be Quiet

- Slider/Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
- Slider/Assets/Scripts/UI/OceanShop/ShopManager.cs
- Slider/Assets/Scripts/UI/UINavigationManager.cs
N/A — Bug reported by Daniel to me :)
Tried it. It worked :)
No
> Re-Do UI Navigation Setup for Tavernkeeper

- Slider/Assets/Materials/Resources/CaveTileLightShader.shadergraph
- Slider/Assets/Materials/Resources/CaveTileLightShaderCustomNodes.hlsl
- Slider/Assets/Prefabs/Managers/GameManager.prefab
- Slider/Assets/Prefabs/Map/Decoration/Caves/PoweredLight.prefab
- Slider/Assets/Scripts/Editor/ConditionalEditor.cs
- Slider/Assets/Scripts/Map/Cave/CaveLight.cs
- Slider/Assets/Scripts/Map/Factory/Conveyor.cs
- Slider/Assets/Scripts/Map/Interactable/Items/Item.cs
- Slider/Assets/Scripts/Map/Props/DiceGizmo.cs
- Slider/Assets/Scripts/Map/Puzzles/ChadRace.cs
- Slider/Assets/Scripts/NPCs/NPC.cs
- Slider/Assets/Scripts/NPCs/NPCWalk.cs
- Slider/Assets/Scripts/NPCs/NPCWalk.cs.meta
- Slider/Assets/Scripts/Systems/GameManager.cs
- Slider/Assets/Scripts/Systems/Save/SaveProfile.cs
- Slider/Assets/Scripts/Systems/VarManager.cs
- Slider/Assets/Scripts/Systems/VarManager.cs.meta
- Slider/Assets/Scripts/UI/Text/TMPSpecialText.cs
- Slider/Assets/Scripts/Utility/Control/Conditionals.cs
- Slider/Assets/Scripts/Utility/Control/DialogueConditionals.cs
- Caves area has power stuff integrated.
- Added NPCWalk.
- You can now setup a walking animation in a dconds. 
- Input a custom path/stile crossings (the intended orientation of the stiles in the path) to allow for movement across stiles
- Extra events: onPathStarted, onPathFinished, onPathBroken, onPathResumed
- Detection for if the path is broken and when it is fixed, so we can handle those cases with dialogue and what not.
- Anchor works while on moving tile!
https://trello.com/c/D9l7nW9L/141-npc-movement
https://trello.com/c/1tiPhG7v/56-anchor-interactions-while-sliding-tile
I played the game a lot.
> NPC New Movement and Anchor Bug Fix

- Slider/Assets/Animations/Characters/NPC/Desert/Bouncer.anim
- Slider/Assets/Prefabs/Interactable/NPC.prefab
- Slider/Assets/Prefabs/Managers/GameManager.prefab
- Slider/Assets/Scripts/NPCs/NPC.cs
- Slider/Assets/Scripts/Sliders/Grid/SGridAnimator.cs
…Arch, Chad
- Desert scene has integrated movement paths for certain NPCs.
- Jackal - Moves to get bone/back. Moves to Oasis.
- Baboon - Moves to Oasis
- Gazelle - Moves to Oasis
- Crocodile - Swims from start to Oasis
- Archeologist - Moves from Oasis to Fossils
- 
- Chad - Dice puzzle is triggered with player input.
By playing through the Desert a lot.
> Updated Desert Scene with New Dialogue

- Slider/Assets/Scenes/Jungle.unity.meta
jungle scene deleted and replaced with jungle dev scene
N/A
game still works woohoo
> jungle scenes merged

- Slider/Assets/Misc/Input/Controls.cs
- Slider/Assets/Misc/Input/Controls.cs.meta
- Slider/Assets/Misc/Input/InputRebindButton.cs
- Slider/Assets/Prefabs/Managers/GameManager.prefab
- Slider/Assets/Scenes/MainMenu.unity
- Slider/Assets/Scripts/Misc/Singleton.cs
- Slider/Assets/Scripts/Misc/Singleton.cs.meta
- Slider/Assets/Scripts/Player/Player.cs
- Slider/Assets/Scripts/UI/Effects/UIEffects.cs
- Slider/Assets/Scripts/UI/MainMenu/MainMenuManager.cs
- Slider/Assets/Scripts/UI/UIManager.cs
- Slider/Assets/Scripts/UI/UINavigationManager.cs
This PR unfortunately contains two rather unrelated tasks — the first is the introduction of two new classes to help clean up the code base. The other is making UI Navigation better.
Keyboard/Mouse Modes for UI Navigation
Tested all core UI functionality in Main Menu and Village. Also did basic gameplay stuff like moving, interacting, etc.
> Add Singleton and Controls Classes, Create UI Navigation Keyboard/Mouse Mode

- Slider/Assets/Prefabs/UI/UIEffects.prefab
- Slider/Assets/Scripts/Misc/PlayTimer.cs
- Slider/Assets/Scripts/Systems/Save/SaveSystem.cs
- Slider/Assets/Scripts/UI/Effects/UIHints.cs
> If this doesn't fix hints i will be sadge

- Slider/Assets/Scenes/MainMenu.unity
- Slider/Assets/Scripts/UI/CutsceneManager.cs
QWERTY Keyboard
Skipping on fadein types out all text
If waiting and skip, start fadeout at 2x speed
If fading out, skip finishes fadeout.
Click click click. But my Asian eyes can't see.
> Save Chase Some Brain and Intro Cutscene Skipping Changes

- Slider/Assets/Misc/Input/InputRebindButton.cs
- Slider/Assets/Prefabs/Managers/GameManager.prefab
> fix rebinds

- Slider/Assets/Misc/Input/Controls.cs
- Slider/Assets/Scenes/MainMenu.unity
- Slider/Assets/Scripts/Audio/AudioManager.cs
- Slider/Assets/Scripts/Misc/Singleton.cs
- Slider/Assets/Scripts/Player/Player.cs
- Slider/Assets/Scripts/UI/SettingsManager.cs
This fixes Singleton to work properly. In particular, overrideExistingInstance has been replaced with overrideExistingInstanceWith, which now takes an instance instead of a bool. It also now actually does what it says, hooray!
This PR also updates AudioManager and SettingsManager to inherit from Singleton.
N/A
Tested Main Menu, Village, and Ocean to make sure saving, settings, and music/sound all still worked.
> Singlify AudioManager and SettingsManager, fix Singleton base class

- Slider/Assets/Prefabs/UI/UICanvas.prefab
- Slider/Assets/Scenes/MainMenu.unity
- Slider/Assets/Scripts/Misc/Singleton.cs
- Slider/Assets/Scripts/UI/UINavigationManager.cs
Haha it's me again here with another round of super fun UI work
> Switch Main Menu and Pause Menu to using SelectableSets instead of the old way on UINavigationManager

- Slider/Assets/Prefabs/Player/Player.prefab
- Slider/Assets/Scripts/Player/Player.cs
- Slider/Assets/Scripts/Player/PlayerAction.cs
I'm unconvinced these changes will actually work without causing issues. There is definitely some weirdness when the player moves into the item's drop location as its dropping, but I'm unsure if this is really a problem.
This PR is here for testing and refining these improvements before they go into main.
Drop item aim assist
> Testing: Drop Item Aiming Improvements

- Slider/Assets/Scripts/Misc/Singleton.cs
This was no longer used and I hated it to begin with, so it is now ELIMINATED. Also the code in Singleton is cleaner now because of it!
N/A
> Remove Support for allowInactiveDuplicates from Singleton

- Slider/Assets/Animations/Characters/NPC/Chad/Chad.controller
- Slider/Assets/Animations/Characters/NPC/Chad/NeoChad.controller
tried fixing chad animation, hopefully it works
> fix chad animation (again) maybe (github sadge)

- Slider/Assets/Misc/Input/Controls.cs
- Slider/Assets/Scripts/UI/OceanShop/ShopManager.cs
This PR updates Controls.cs with new functionality to better support manually managing binding behaviors. It also makes use of this new feature to fix issues with the Tavernkeeper UI.
This PR **does not** fix the issue where the player can skip needing the anchor before entering the UI by spamming E after getting the slider from being kicked out of the menu for the first time.
[Ocean Tavern Shop is quite broken](https://trello.com/c/JpSAiqOL)
Tried out UI options to make sure they worked properly
> Fix Tavernkeeper Issues, Introduce Unmanaged Binding Behavior

- Slider/Assets/Scenes/Dev/Logan/Factory Elliot.unity.meta
> Scene Merge Fix

- Slider/Assets/Prefabs/Map/Functional/Factory/3D Printer.prefab
- Slider/Assets/Scripts/Map/Factory/Printer.cs
Mini Particle/Factory/Printer update
Tested in scene
> 70% working animation

- Slider/Assets/Prefabs/Map/Functional/Factory/3D Printer.prefab
- Slider/Assets/Scenes/Dev/Koushik/Factory 1.unity.meta
- Slider/Assets/Scripts/Map/Factory/Printer.cs
Finished printer printing animation for now
Printer animates with smoke clouds and animation speed ups
Tested in scene
> 90% Complete Animations, tweak when ParticleManager

- Slider/Assets/Scripts/Map/Factory/Printer.cs
> Fixed Saving issue

- Slider/Assets/Sprites/Items/desert_bottles.png.meta
- Slider/Packages/manifest.json
- Slider/Packages/packages-lock.json
Updated Burst package to 1.8
Everything
This has not been tested
> Testing Burst Update to 1.8 PR

- Slider/Assets/Scripts/Map/Interactable/Collectible.cs
- Slider/Assets/Scripts/Misc/Breadge.cs
- Slider/Assets/Scripts/Misc/Breadge.cs.meta
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/VillageGrid.cs
- Slider/Assets/Scripts/Steamworks.NET/AchievementManager.cs
Add Steam Achievements for Village
[Steam achievements](https://trello.com/c/Ekdx8Pju)
Met conditions, got achievements on Steam.
**Please help me test this!! On this build, keep Steam open and see if you get the achievements. This stuff is kinda finicky**
First ever Slider 100%
> Add Village Achievements

- Slider/Assets/Scripts/AI/Pathfinding/WorldNavigation.cs
- Slider/Assets/Scripts/AI/Rat/RatAI.cs
- Slider/Assets/Scripts/Map/Cave/CaveMossManager.cs
- Rat stays in 3x3 (doesn't go "out of bounds")
- Fixed moss manager dictionary so that it doesn't access bad keys
> Retirement Never Suited Me

- Slider/Assets/Scripts/Map/Ocean/ScavengerHuntBoard.cs
- Slider/Assets/Scripts/Map/Ocean/ScavengerHuntBoard.cs.meta
- Slider/Assets/Scripts/UI/OceanShop/ShopDialogueManager.cs
- Slider/Assets/Scripts/UI/OceanShop/ShopManager.cs
scav board in tavern now displays available things the player can look for based on the tiles they have acquired and updates when the player turns in something!
> scav board implemented!

- Slider/Assets/Scripts/Map/Mountain/Minecart/Minecart.cs
- Slider/Assets/Scripts/Player/PlayerAction.cs
- Slider/Assets/Sprites/Characters/Factory/construction-worker-spritesheet.png.meta
- Slider/Assets/Sprites/Characters/Factory/future_tech-Sheet.png.meta
- Slider/Assets/Sprites/Characters/Factory/scientist-Engineer-Sheet.png.meta
- Slider/Assets/Sprites/Characters/Mountain/crystal_miners-Sheet.png.meta
- Slider/Assets/Sprites/Characters/ocean/pirate7.png.meta
- Slider/Assets/Sprites/Characters/ocean/pirate8.png.meta
- Slider/Assets/Sprites/Characters/ocean/pirates.png.meta
See title
Boomo's Summons
Yes
No
> Fix an issue where spamming E allowed picking up an item while dropping it

- Slider/Assets/Scripts/Player/PlayerAction.cs
> Fix bug where NPCs changing dconds would prevent the player from throwing a held item

- Slider/Assets/Scripts/UI/OceanShop/ShopDialogueManager.cs
y'all need to learn how to spell
went through dialogue with carr and brushed up some bs
N/A
if this breaks the game...
> ocean dialogue polish

- Slider/Assets/Materials/Resources/CaveTileLightShader.shadergraph
> Fix Caves Shader fr fr

- Slider/Assets/Scripts/Audio/MaterialBasedEmitter.cs
- Slider/Assets/Scripts/Map/ISTileLocatable.cs
- Slider/Assets/Scripts/Player/Player.cs
> fmod refactor

- Slider/Assets/Materials/Pixelate.mat
- Slider/Assets/Materials/Pixelate.mat.meta
- Slider/Assets/Materials/Render Textures/Desert RT.renderTexture
- Slider/Assets/Materials/Render Textures/Desert RT.renderTexture.meta
- Slider/Assets/Materials/Resources/PixelatedLR.shadergraph
- Slider/Assets/Materials/Resources/PixelatedLR.shadergraph.meta
Line Renderer more like Poopoo Peepee (this is a reference to the fact that the Line Renderer sucks)
> Pixelate Baboon Rope

- Slider/Assets/Scripts/Audio/Dialogue/BasicVocalizer.cs
- Slider/Assets/Scripts/Audio/Dialogue/IVocalizer.cs
- Slider/Assets/Scripts/Audio/Dialogue/SentenceVocalizer.cs
- Slider/Assets/Scripts/Audio/Dialogue/VocalizerPreset.cs
- Slider/Assets/Scripts/Audio/Dialogue/WordVocalizer.cs
> something else

- Slider/Assets/Scripts/Audio/AudioManager.cs
> fix pause menu

- Slider/Assets/Prefabs/Managers/AudioManager.prefab
- Slider/Assets/Scripts/Audio/AudioManager.cs
- Slider/Assets/Scripts/Audio/Dialogue/BasicVocalizer.cs
- Slider/Assets/Scripts/Audio/SoundWrapper.cs
- Slider/Assets/Scripts/UI/UIArtifactMenus.cs
> Ducklings and buglings

- Slider/Assets/Scripts/AI/Rat/RatAI.cs
- Slider/Assets/Scripts/Map/Factory/Conveyor.cs
- Slider/Assets/Scripts/Map/Factory/PastLargeCrystal.cs
- Slider/Assets/Scripts/Map/Interactable/Items/AnchorFirstAppearance.cs
- Slider/Assets/Scripts/Map/Interactable/Items/BootsSpeedIncrease.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/CaveGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/DesertGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/FactoryGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/JungleGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/MountainGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/OceanGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/SGrid.cs
- Slider/Assets/Scripts/UI/Debug/DebugUIManager.cs
NOTE: New achievements have been added in steamworks but have not been published. Cannot test in steam until they are published. They should probably also be crossreferenced for typos (which I did but i might have messed up)
All achievements have been added in steamworks except for those not finalized (desert, mountain, military, magitech challenges)
New Achievements:
-Completion: caves, ocean, jungle, desert, factory, mountain
-Collection: Anchor, boots, scroll
-Savior
Fixed Achievements:
-Rat tiles visited is now serialized, all currently active tiles needed
-Linked min ocean anchors to achievement manager
Other Changes
-removed outdated rat AI code
-added debug command to toggle conveyers off 
-fixed factory tile numbering, grid check, minor typos
> More Achievements

- Slider/Assets/Scripts/AI/Rat/RatAI.cs
> rat hotfix

- Slider/Assets/Prefabs/Interactable/NPC.prefab
- Slider/Assets/Scripts/Audio/Dialogue/BasicVocalizer.cs
> Floating point safety

- Slider/Assets/Scripts/NPCs/DialogueDisplay.cs
- Slider/Assets/Scripts/UI/Text/TMPTextTyper.cs
> thoroughly wrapped

- Slider/Assets/Prefabs/Interactable/Items/ConductiveBob.prefab
- Slider/Assets/Scripts/Map/Factory/FactoryTimeManager.cs
- Slider/Assets/Scripts/Map/Interactable/Items/TrackableItem.cs
- Slider/Assets/Scripts/Map/Interactable/Items/TrackableItem.cs.meta
Make bob trackers not show when picked up
https://trello.com/c/EMfWyGh1/387-make-carried-bobs-not-show-uitracker-or-track-player
went to past/present and verified only correct trackers show. picked up bob and tracker goes away
> Fix Bob Trackers

- Slider/Assets/Scenes/Dev/Vocalizer Test.unity.meta
- Slider/Assets/Scripts/Player/Player.cs
> Add Vocalizer Test Scene

- Slider/Assets/Scripts/Audio/AudioManager.cs
> bug duck duck bug

- Slider/Assets/Scripts/Audio/STileSoundTransform.cs
- Slider/Assets/Scripts/Audio/STileSoundTransform.cs.meta
- Slider/Assets/Scripts/Sliders/Grid/MountainSGridAnimator.cs
- Slider/Assets/Scripts/Sliders/Grid/SGridAnimator.cs
- Slider/Assets/Scripts/Sliders/SMove/SMove.cs
Ocean,  jungle double tile, and desert tile now all play 1 sound only instead of  4, 2, and potentially 8 respecitvely 
lots of prints, clicking and hoping my ears dont die (they didnt)
> Your ears have been saved

- Slider/Assets/Scripts/Audio/Dialogue/WordVocalizer.cs
Reproduced bug in vocalizer test, verified it's gone. Not pushing changes made to the scene.
> Account for no vowel words

- Slider/Assets/Scripts/Misc/Hints/PlayerActionHints.cs
- Slider/Assets/Scripts/UI/Effects/UIHints.cs
-Restructured hint to include HintData class with all items related to actual hint display
-UI hints now update in real time and use a list of HintData instead of static text
-Updated all hints to use new format
-If a hint is completed while another is queued, only the text fades, not the whole textbox
-Press E to pick up items hint now requires you to pick up items
-Minor adjustments to hint timing and wording
> A hint of polish

- Slider/Assets/Scripts/Map/MagiTech/MagiLaserFlash.cs
> magitech laser order fix

- Slider/Assets/Scripts/Editor/NPCConditionalsDrawer.cs
- Slider/Assets/Scripts/NPCs/NPCConditionals.cs
> OR option for conditionals

- Slider/Assets/Prefabs/UI/UICanvas.prefab
- Slider/Assets/Scripts/Input/Controls.cs
- Slider/Assets/Scripts/NPCs/DialogueDisplay.cs
- Slider/Assets/Scripts/Player/Player.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaSTiles/MirageSTileManager.cs
- Slider/Assets/Scripts/UI/Rebinding/ControlsMenuPanelHandler.cs
- Slider/Assets/Scripts/UI/Rebinding/RebindingButton.cs
- Slider/Assets/Scripts/UI/UIManager.cs
- Slider/Assets/Scripts/UI/UINavigationManager.cs
Also fix some annoying warnings and errors in the console
> Fix controller bindings showing for keyboard rebind buttons, make rebind buttons unselectable with controller

- Slider/Assets/Prefabs/Player/Player.prefab
- Slider/Assets/Prefabs/UI/Panels/ControlsPanel.prefab
- Slider/Assets/Prefabs/UI/UICanvas.prefab
- Slider/Assets/Scenes/MainMenu.unity
- Slider/Assets/Scripts/UI/Rebinding/RebindingButton.cs
Fixed NREs and some buttons that did thr wrong thing
I tried harder
> Travis' dirty work

- Slider/Assets/Prefabs/UI/Panels/AdvOptionsPanel.prefab
- Slider/Assets/Prefabs/UI/Panels/ControlsPanel.prefab
- Slider/Assets/Prefabs/UI/Panels/OptionsPanel.prefab
- Slider/Assets/Prefabs/UI/UICanvas.prefab
- Slider/Assets/Scenes/MainMenu.unity
- Slider/Assets/Scripts/Audio/AudioManager.cs
- Slider/Assets/Scripts/Audio/MaterialBasedEmitter.cs
- Slider/Assets/Scripts/Effects/CameraDolly.cs
- Slider/Assets/Scripts/Input/Controls.cs
- Slider/Assets/Scripts/Map/MagiTech/ReflectionPool.cs
- Slider/Assets/Scripts/Map/Ocean/OceanDolly.cs
- Slider/Assets/Scripts/Map/SceneChanger.cs
- Slider/Assets/Scripts/Player/PlayerAction.cs
- Slider/Assets/Scripts/Sliders/Grid/SGrid.cs
- Slider/Assets/Scripts/UI/Artifact/Tabs/ArtifactTabManager.cs
- Slider/Assets/Scripts/UI/CursorVisibility.cs
- Slider/Assets/Scripts/UI/Debug/DebugUIManager.cs
- Slider/Assets/Scripts/UI/Effects/ItemPickupEffect.cs
- Slider/Assets/Scripts/UI/MainMenu/MainMenuSaveButton.cs
- Slider/Assets/Scripts/UI/MainMenu/SavePanelManager.cs
- Slider/Assets/Scripts/UI/OceanShop/ShopManager.cs
- Slider/Assets/Scripts/UI/PauseManager.cs
- Slider/Assets/Scripts/UI/PauseManager.cs.meta
- Slider/Assets/Scripts/UI/PausePanelHandler.cs
- Slider/Assets/Scripts/UI/PausePanelHandler.cs.meta
- Slider/Assets/Scripts/UI/UIArtifactMenus.cs
- Slider/Assets/Scripts/UI/UIManager.cs
- Slider/Assets/Scripts/UI/UIMenu.cs
- Slider/Assets/Scripts/UI/UINavigationManager.cs
> UI refactoring (Part 3)

- Slider/Assets/Scripts/UI/CursorVisibility.cs
- Slider/Assets/Scripts/UI/Debug/DebugUIManager.cs
if i had a nickel for every time I had to fix a bug for travis I'd have 2 nickels
> make cursor visible on debug again

- Slider/Assets/Scripts/Player/Player.cs
> fix jungle outline bug

- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/MagiTechGrid.cs
- Slider/Assets/Scripts/UI/Artifact/AreaArtifacts/MagiTech/MagiTechArtifact.cs
also moved grid code to grid instead of artifact because that's where it belongs
> fix desync not resetting on leaving magitech

- Slider/Assets/Prefabs/Map/Functional/Jungle/Double sign.prefab
- Slider/Assets/Prefabs/Map/Functional/Jungle/FairyHouse.prefab
- Slider/Assets/Prefabs/Map/Functional/Jungle/Sign.prefab
- Slider/Assets/Prefabs/UI/Artifact/FragRealigningTab Variant.prefab
- Slider/Assets/Scripts/Map/Jungle/JungleSignAnimator.cs
Added functions in JungleSignAnimator and modified prefabs so that changing the shape is done via sign plus sign change animation
Overloaded the BumpAnimation function and added changeShape function for JungleSignAnimator
Removed player conditional on prefab of fairy houses 
https://github.com/randomerz/Slider/assets/37708746/bf4de090-4b1a-4726-8f7b-bcded13af1f4
> Jungle Shape Sign

- Slider/Assets/Scripts/Sliders/Grid/SGridAnimator.cs
- Slider/Assets/Scripts/Sliders/SMove/SMove.cs
I've seen some whack ass bugs before but this one might take the cake lol
-fixed bug
i tried it and th ebug is fixed
> Fix magitech borders bug

- Slider/Assets/Scripts/Map/MagiTech/DesyncLever.cs
- Slider/Assets/Scripts/UI/Artifact/AreaArtifacts/MagiTech/MagitechUITrackerManager.cs
- Slider/Assets/Scripts/UI/Artifact/Misc/LaserUIOffMap.cs
- Slider/Assets/Scripts/UI/Artifact/Misc/LaserUIOffMap.cs.meta
- Slider/Assets/Scripts/UI/Artifact/Plugins/ArtifactTBPluginLaser.cs
- Slider/Assets/Scripts/UI/Artifact/Trackers/UITrackerManager.cs
-Fixed outer world UI trakcers showing in wrong dimension
-Laser into desert portal now shown on artifact UI when desert portal is enabled 
-Fixed desync lever to work as intended
> Minor Magitech Fixes

- Slider/Assets/Materials/UI Default.mat
- Slider/Assets/Prefabs/UI/Artifact/ArtifactCanvas.prefab
- Slider/Assets/Scripts/Misc/FollowTarget.cs
- Slider/Assets/Scripts/Misc/FollowTarget.cs.meta
- Slider/Assets/Scripts/UI/Artifact/AreaArtifacts/MagiTech/MagiTechArtifact.cs
- Slider/Assets/Scripts/UI/Artifact/AreaArtifacts/Mountain/MountainArtifactButton.cs
- Slider/Assets/Scripts/UI/Artifact/ArtifactTileButton.cs
- Slider/Assets/Scripts/UI/Artifact/UIArtifact.cs
-Lightning now follows a parent transform
-Lightning now masks properly
-Mountain buttons animate from the proper direction
-Fixed some initialization errors with magitech buttons
-Cleaned up old comments
> Fix Lightning Masking

- Slider/Assets/Scripts/UI/Artifact/Tabs/ArtifactTabManager.cs
> Fix scroll hover preview UI desync

- Slider/Assets/Scripts/UI/UIArtifactMenus.cs
> disable artifact navigation w keyboard

- Slider/Assets/ScriptableObjects/Jungle/Recipes/HeartRecipe.asset
happy m23 this makes the game fully playable in theory
> Fix recipe

- Slider/Assets/Scenes/MainMenu.unity
- Slider/Assets/Scripts/UI/MainMenu/KeyboardButton.cs
-fixed bug where the profile character limit was ignored when using the on-screen keyboard
> No infinite length profiles for you

- Slider/Assets/Prefabs/Interactable/Items/Jungle Item.prefab
- Slider/Assets/Prefabs/Interactable/Items/Jungle Item.prefab.meta
- Slider/Assets/Prefabs/Map/Functional/Jungle/Blob.prefab
- Slider/Assets/Scenes/Dev/Allison/Jungle 1.unity.meta
- Slider/Assets/Scripts/Map/Jungle/Blob.cs
- Slider/Assets/Scripts/Map/Jungle/Box.cs
- Slider/Assets/Scripts/Map/Jungle/Path.cs
- Slider/Assets/Scripts/Map/Jungle/ShapePlacer.cs
- Slider/Assets/Scripts/Map/Jungle/Sign.cs
- Slider/Assets/Sprites/Items/jungle_items.png.meta
Fixed a couple of blob bugs
- Blob off path
- Sign not sending blobs on the right path
- Chase mentioned these in Discord
I played the game and didn't run into the bugs anymore
> Fix path blob bugs

- Slider/Assets/Scripts/Sliders/Grid/AreaSTiles/MirageSTileManager.cs
- Slider/Assets/Scripts/Sliders/Grid/SGridAnimator.cs
- Slider/Assets/Scripts/UI/Artifact/UIArtifact.cs
> fix mirage

- Slider/Assets/Scripts/UI/Effects/UIEffects.cs
> Fix UI effect bug

- Slider/Assets/Scripts/Map/Desert/DesertCasino.cs
you can no longer complete dice without casino together
> Fix dice bug

- Slider/Assets/Scripts/UI/Artifact/ArtifactTileButton.cs
- Slider/Assets/Scripts/UI/Artifact/UIArtifact.cs
> fix conveyer UI flicker

- Slider/Assets/Scripts/Map/Jungle/Box.cs
- Slider/Assets/Scripts/Map/Jungle/Hut.cs
(title)
Just added the thing to the method i overrode
> Huts also renew path pairs when stile enable

- Slider/Assets/Scripts/UI/OceanShop/ShopDialogueManager.cs
Updated some of Bob's dialogue.
Update Bob's Dialogue
It compiled
> Updated Bob's Dialogue

- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/OceanGrid.cs
Don't ask about the branch name i dont wanna talk about it
> Fix ocean completion and Justin dconds

- Slider/Assets/Materials/SpriteParticleBoatRipple.mat
- Slider/Assets/Materials/SpriteParticleGroundLightning.mat
- Slider/Assets/Materials/SpriteParticleRocketSmoke.mat
- Slider/Assets/Materials/SpriteParticleSmoke.mat
- Slider/Assets/Materials/SpriteParticleSparks.mat
- Slider/Assets/Materials/lava Particles.mat
- Slider/Assets/Scripts/Map/Factory/PastLargeCrystal.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/CaveGrid.cs
-Made all particle materials unlit
-Fixed easy resources.load uses
> Small Particle Fixes

- Slider/Assets/Scripts/UI/Artifact/AreaArtifacts/MagiTech/MagiTechArtifact.cs
https://trello.com/c/eK65V5KM/608-if-you-click-hold-down-a-button-on-magitech-preview-it-stays
> fix drag and drop w magitech preview

- Slider/Assets/Scripts/Map/Interactable/Items/DesyncItem.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/MagiTechGrid.cs
> Desync Item Rework Any% Speedrun

- Slider/Assets/Scripts/Map/Military/Travis/ArtifactUnitIconHandler.cs
- Slider/Assets/Scripts/Map/Military/Travis/MilitaryTurnManager.cs
- Slider/Assets/Scripts/Map/Military/Travis/MilitaryTurnManager.cs.meta
- Slider/Assets/Scripts/Map/Military/Travis/MilitaryUnit.cs
- Slider/Assets/Scripts/Map/Military/Travis/MilitaryUnitCommander.cs
- Slider/Assets/Scripts/Map/Military/Travis/MilitaryUnitFlag.cs
- Slider/Assets/Scripts/Map/Military/Travis/MilitaryUnitFlag.cs.meta
- Slider/Assets/Scripts/Map/Military/Travis/MoveTowardsStrategy.cs
See title
I got kicked from the Trello :(
Not really
> Make military not break the game and also work (mostly)

- Slider/Assets/Animations/Tiles and Props/Mountain/HeaterCoilOn.controller
- Slider/Assets/Animations/Tiles and Props/Mountain/HeaterCoilOn.controller.meta
- Slider/Assets/Scripts/Map/Interactable/Items/Item.cs
- Slider/Assets/Scripts/Map/Mountain/GemMachine.cs
- Slider/Assets/Scripts/Map/Mountain/Minecart/Minecart.cs
- Slider/Assets/Scripts/Map/Mountain/WaterWheel.cs
- Slider/Assets/Scripts/Map/Mountain/WaterWheelAnimator.cs
- Slider/Assets/Scripts/Player/PlayerAction.cs
fixed a few bugs and made some design tweaks
-fixed NRE with cave wall and minecart
-you can break frozen slider w anchor now (fr fr)
-added 2nd NPC for heater
-replaced oil w toolbox item (using wire cutters sprite as temp)
-all heaters now turn on when pipe is full 
-fixed gem machine serialization
> Some mountain fixes

- Slider/Assets/Prefabs/Map/Functional/Factory/TimedGate.prefab
- Slider/Assets/Scripts/Utility/Control/CarriedItemLayerChanger.cs
- Slider/Assets/Scripts/Utility/Control/CarriedItemLayerChanger.cs.meta
wrong branch oops
-fixes timed gate diodes rendering on top of items
-fixes fence rendering on top of anchor
> fix factory render issues

- Slider/Assets/Prefabs/UI/Artifact/ArtifactButton.prefab
- Slider/Assets/Scripts/UI/Artifact/JungleButtonMiddleAnimator.cs
- Slider/Assets/Scripts/UI/Artifact/Tabs/ArtifactTabManager.cs
- Slider/Assets/Sprites/UI/AreaIcons/Areas/ArtifactIcons.png.meta
- Slider/Assets/Sprites/UI/artifact/ControllerHoverHighlight.png.meta
-Fixed possible NRE from using scroll during moves by tracking coroutines
-Fixed Jungle hover/selected/controller hover icons on long tile
-Fixed bob UI on widescreen/16:10/etc
> Me when scroll bug

- Slider/Assets/Scripts/UI/Artifact/AreaArtifacts/MagiTech/MagiTechArtifact.cs
> Magitech NRE fix

- Slider/Assets/Scripts/Map/Mountain/MoveObjectsOffIce.cs
minecart drop puzzle
minecart drop puzzle
minecart drop puzzle
> minecart drop puzzle

- Slider/Assets/Scripts/Map/Desert/DesertTemple.cs
- Slider/Assets/Scripts/Player/Player.cs
- Slider/Assets/Scripts/UI/Settings/SettingsManager.cs
what it says
also fixed edge case i think where if you loaded save in temple the tracker could be enabled
> Redraw player icon on settings change

- Slider/Assets/Scripts/Map/Ocean/BottleManager.cs
- Slider/Assets/Scripts/UI/OceanShop/ShopDialogueManager.cs
-Fixed some typos
-tweaked dialogue 
-Added extra conditions to bottle dialogue
> ocean playtest fixes

- Slider/Assets/Prefabs/UI/Panels/DisplayPanel.prefab
- Slider/Assets/Scripts/UI/Settings/GraphicsSettingsManager.cs
- Slider/Assets/Scripts/UI/Settings/ResolutionSettingRetriever.cs
> native resolution option

- Slider/Assets/Materials/Resources/UIDarken.shader
- Slider/Assets/Materials/Resources/UIDarken.shader.meta
- Slider/Assets/Materials/Resources/UIDarken.shadergraph
- Slider/Assets/Materials/Resources/UIDarken.shadergraph.meta
- Slider/Assets/Materials/UIDarken.mat
- Slider/Assets/Materials/UIDarken.mat.meta
> UI Darken Shader

- Slider/Assets/Scripts/UI/Artifact/Magitech/UILaserManager.cs
> Fix desert laser UI bug

- Slider/Assets/Scripts/Player/Player.cs
- Slider/Assets/Scripts/UI/Artifact/Trackers/UITrackerManager.cs
> fix player UI tracker

- Slider/Assets/Scripts/Map/Mountain/GemMachine.cs
- Slider/Assets/Scripts/Map/Mountain/LavaFallBottom.cs
- Slider/Assets/Scripts/Map/Mountain/Minecart/Minecart.cs
- Slider/Assets/Scripts/Map/Mountain/Minecart/MinecartElevator.cs
- Slider/Assets/Scripts/Map/Mountain/Minecart/RailManager.cs
- Slider/Assets/Scripts/Map/Mountain/WaterWheel.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/MountainGrid.cs
- Slider/Assets/Sprites/Tiles/mountain/Rail Tile Assets/Scriptable Rails/W Line End.Asset
-moved barrier rail tiles so you can't place minecart inside of barriers
-minecart now snaps to ice rail tiles
-fixed snap to rails ignoring item colliders
-fixed minecart UI tracker not being removed on pickup
-fixed extra minecart UI trackers spawning when they shouldn't
-minecart state no longer erroniously saved
-minecart state setting uses enum instead of string
-small dialogue/dcond tweaks
> Fix Minecart bugs

- Slider/Assets/Scripts/Map/MagiTech/GemManager.cs
- Slider/Assets/Scripts/NPCs/Misc/ChadFollowPlayer.cs
- Slider/ProjectSettings/ProjectSettings.asset
Fixed a bunch of softlocks 
-Chad portal gun in factory and desert scenes
-Lots of chad follow NRE
-Mountain tile 7 not given 
-magitech gfuel and gem check was wrong
known but not fixed: 
2 military aliens can move onto same square, only 1 tile dropped
player can spawn in void in military
> Fix speedrun softlocks

- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/MilitaryGrid.cs
- Slider/Assets/Scripts/UI/Effects/UIEffects.cs
also maybe fix that weird pixelization bug but probably not
> fix military player spawn

- Slider/Assets/Fonts/NotoSans Variants/Languages/NotoSansJP-Bold SDF.asset.meta
- Slider/Assets/Prefabs/Map/Functional/Mountain/Lavafall.prefab
- Slider/Assets/Prefabs/Map/Functional/Mountain/Waterfall.prefab
- Slider/Assets/Scripts/Audio/Ambience/DistanceBasedAmbience.cs
- Slider/Assets/Scripts/Map/Mountain/Minecart/Minecart.cs
- Slider/Assets/Sprites/Tiles/mountain/Minecart Rails Tileset.png.meta
-added ambience for lava, lavafall, waterfall, gems, minecart
-serialized item positions
-hat click and particles when minecart snaps to rails
-removed left rail from ice dropdown
-fixed dconds for waterwheel dude 
-fixed junction UI indicator that was wrong
> Mountain fixes

- Slider/Assets/Scripts/Map/Interactable/Items/DesyncItem.cs
- Slider/Assets/Scripts/Map/Interactable/Items/ItemPlacerSolver.cs
> me when desync item

- Slider/Assets/Scripts/UI/Settings/GraphicsSettingsManager.cs
> Fix Native Resolution

- Slider/Assets/Scripts/Map/Desert/DesertTemple.cs
> Fix temple music bug

- Slider/Assets/Prefabs/Interactable/Items/Anchor.prefab
- Slider/Assets/Scripts/Map/Interactable/Items/Anchor.cs
- Slider/Assets/Scripts/Map/Interactable/Items/AnchorFirstAppearance.cs
> anchor splash particles

- Slider/Assets/Scripts/Map/Mountain/WaterWheelAnimator.cs
> mountain fixes for boomo

- Slider/Assets/Scripts/AI/Rat/RatAI.cs
- Slider/Assets/Scripts/EndOfGame/EndOfGameManager.cs
- Slider/Assets/Scripts/Map/Desert/DesertTemple.cs
- Slider/Assets/Scripts/Map/Factory/PastLargeCrystal.cs
- Slider/Assets/Scripts/Map/Interactable/Collectible.cs
- Slider/Assets/Scripts/Map/Interactable/Items/AnchorFirstAppearance.cs
- Slider/Assets/Scripts/Map/Interactable/Items/BootsSpeedIncrease.cs
- Slider/Assets/Scripts/Map/Jungle/RecipeBook/JungleRecipeBook.cs
- Slider/Assets/Scripts/Map/MagiTech/ReflectionPool.cs
- Slider/Assets/Scripts/Map/Military/MilitaryWaveManager.cs
- Slider/Assets/Scripts/Map/Mountain/CrystalHopper.cs
- Slider/Assets/Scripts/Misc/Breadge.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/CaveGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/DesertGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/FactoryGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/JungleGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/MagiTechGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/MountainGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/OceanGrid.cs
- Slider/Assets/Scripts/Sliders/Grid/AreaGrids/VillageGrid.cs
- Slider/Assets/Scripts/Steamworks.NET/AchievementManager.cs
- Slider/Assets/Scripts/UI/Debug/DebugUIManager.cs
> No challenge achievements if you cheat

- Slider/Assets/Scripts/Map/Interactable/Items/DesyncItem.cs
- Slider/Assets/Scripts/Map/Interactable/Items/ItemPlacerSolver.cs
> I LOVE DESYNC ITEM I LOVE DESYNC ITEM I LOVE DESYNC ITEM

- Slider/Assets/Scripts/Map/Desert/DinoLaser.cs
- Slider/Assets/Scripts/Map/Desert/DinoLasersManager.cs
- Slider/Assets/Scripts/UI/Artifact/Plugins/ArtifactTBPluginMirage.cs
-Fixed events not being subscribed to properly, causing save/load to completely brick the dino laser
-Fixed bug where activation animation could be interupted but still continue
-Fixed NRE in laser UI when loading with mirage enabled
> I LOVE DINO LASER I LOVE DINO LASER I LOVE DINO LASER

- Slider/Assets/Prefabs/Map/Functional/MagiTech/Mirror1.prefab
- Slider/Assets/Prefabs/Map/Functional/MagiTech/Mirror1Past Variant.prefab
- Slider/Assets/Scripts/Map/Interactable/Items/DesyncItem.cs
> Fix desync items w scroll

- Slider/Assets/Scripts/Map/Mountain/MoveObjectsOffIce.cs
> fix one case of mountain softlock

- Slider/Assets/Scripts/Audio/Dialogue/IVocalizerComposite.cs
- Slider/Assets/Scripts/UI/OceanShop/ShopDialogueManager.cs
- Slider/Assets/Scripts/UI/OceanShop/ShopManager.cs
> NRE and general shop dialogue fixes

- Slider/Assets/Scripts/Map/Ocean/FoggySeasManager.cs
-foggy island fades in
-music notes stay until you leave island
-island disapears when going off map
> foggy seas improvements

- Slider/Assets/Materials/Render Textures/Item RT.renderTexture
- Slider/Assets/Materials/Render Textures/MountainCamRT.renderTexture
- Slider/Assets/Prefabs/Particles/Resources/LavaParticles.prefab
- Slider/Assets/Scripts/Effects/CameraZoom.cs
- Slider/Assets/Scripts/Effects/OverlayCameraImageScaler.cs
- Slider/Assets/Scripts/Map/MagiTech/MagiLaser.cs
- Slider/Assets/Scripts/UI/Artifact/Magitech/UILaserManager.cs
-fixed water/lavafall UI placement
-fixed magitech laser UI not disabling when laser is off
-rescaled mountain render texture from 2x screen size to 1.25x screen size
> Misc fixes

- Slider/Assets/Scripts/NPCs/Misc/ChadFollowPlayer.cs
> No chad blur

- Slider/Assets/Scripts/Sliders/Grid/AreaSTiles/MirageSTileManager.cs
> fix mirage bug why the f am i on ocean branch

- Slider/Assets/Scripts/Map/Military/AI/MoveTowardsStrategy.cs
- Slider/Assets/Scripts/Map/Military/MilitaryWaveManager.cs
- Slider/Assets/Scripts/Map/Military/Unit/MilitaryUnspawnedAlly.cs
- Slider/Assets/Scripts/Systems/Save/SaveProfile.cs
- Slider/Assets/Scripts/Systems/Save/Serializables/SerializableSaveProfile.cs
- Slider/Assets/Scripts/UI/Artifact/AreaArtifacts/DesertArtifactRandomizer.cs
- Slider/Assets/Scripts/Utility/SeededRandom.cs
- Slider/Assets/Scripts/Utility/SeededRandom.cs.meta
> RNG is dead

- Slider/Assets/Sprites/LargeProps/jungle/Trees/large_tree_9.png.meta
> fix jungle bridge sorting

- Slider/Assets/Scripts/AI/Rat/RatAI.cs
> Rat race version 3 :sob:

- Slider/Assets/Scripts/Map/Mountain/MountainSoftlockChecker.cs
> this game has gone WOKE. i am UNSUBSCRIBING

- Slider/Assets/Scripts/Map/Mountain/Minecart/MinecartElevator.cs
> wake up babe new gamebreaking mountain strat dropped

- Slider/Assets/Scripts/Map/MagiTech/MagitechMoveOffMoss.cs
- Slider/Assets/Scripts/Map/MagiTech/MagitechMoveOffMoss.cs.meta
- Slider/Assets/Scripts/Map/Military/MilitaryCollectibleController.cs
> magitech mushrooms push you off

- Slider/Assets/Prefabs/UI/DebugCanvas.prefab
- Slider/Assets/Scripts/Map/Mountain/Minecart/Minecart.cs
- Slider/Assets/Scripts/Steamworks.NET/AchievementManager.cs
- Slider/Assets/Scripts/UI/Debug/DebugUIManager.cs
-if minecart dropdown aborts, minecart no longer stuck trying to drop
-replaced spawn all tiles button with respawn button on debug canvas
> Fix minecart dropdown

- Slider/Assets/Scripts/EndOfGame/EndOfGameManager.cs
> fix speedrun achievements

- Slider/Assets/Scripts/EndOfGame/EndOfGameManager.cs
- Slider/Assets/Scripts/Steamworks.NET/AchievementManager.cs
- Slider/Assets/Scripts/UI/Options/CheatsControlPanel.cs
> tp w/o setting cheated

- Slider/Assets/Scripts/Misc/SimpleInteractableCutscene.cs
- Slider/Assets/Scripts/NPCs/NPC.cs
- Slider/Assets/Scripts/NPCs/NPCDialogueContext.cs
- Slider/Assets/Scripts/UI/Artifact/ArtifactTileButton.cs
- Slider/Assets/Scripts/UI/Artifact/Tabs/DesertTabManager.cs
- Slider/Assets/Scripts/UI/Options/CheatsControlPanel.cs
i was gonna fix more stuff but i looked at the list on trello and i dont wanna do any of it 💀
> Disable ... in cutscene, gray out scroll when middle tile anchored

- Slider/Assets/StreamingAssets/Localizations/简体中文/_简体中文_configs.csv
> desert proofread 2: sandy boogaloo
