randomerz/Slider

Slider/Assets/Scripts/UI/Artifact/ArtifactTileButton.cs, Slider/Assets/Scripts/UI/Artifact/UIArtifact.cs, Slider/Assets/Scripts/UI/UIManager.cs
Added a coroutine to ArtifactTileButton.cs that flickers the tiles, as well as a method to start the coroutine. Currently the Tile flickers twice upon opening the Artifact, but that can be changed fairly easily. Added a method to UIArtifact.cs that checks if any tiles are new and then calls Flicker() if they are.
New Slider Effect
Have checked through all tiles in the village, as well as the two that I can currently find in the cave.
As far as I can tell, should not affect any other areas in the code, other than adding a possible less than a millisecond delay after opening the artifact menu, where it checks to see if any of the tiles are new.
=> New Tiles Now Flicker

Slider/Assets/Scripts/UI/Artifact/UIArtifact.cs
Currently the Queue only works up to another move ahead, if any more wants to happen, we need to change how swap is implemented. I also deactivated the waterfall entrance until the bug is fixed, whatever it is.
Slider Animation Queue
I have only been able to find the bug with the waterfall entrance currently. Otherwise, I have tested it with the other entrances in the map, including all 3 cave exits, as well as just tested it with multiple tiles with or without the player on them.
=> Queue Implemented

Slider/Assets/Scripts/Sliders/Grid/SGrid.cs, Slider/Assets/Scripts/Sliders/SMove/SMove.cs, Slider/Assets/Scripts/UI/Artifact/ArtifactTileButton.cs, Slider/Assets/Scripts/UI/Artifact/ArtifactTileButtonAnimator.cs, Slider/Assets/Scripts/UI/Artifact/UIArtifact.cs, Slider/Assets/Scripts/UI/UIManager.cs, Slider/Packages/manifest.json, Slider/Packages/packages-lock.json
- Queue can now buffer up to 2 moves in advance (variable). 
- The buttons now move instantaneously, so the move options are always up to date.
- You don't have to reclick a button to make another move
- Drag and Drop might still be broken idk.
- Changed the Swap function by taking out certain parts of it and also added a flag that causes it to only update the artifact and not the grid.
Slider animation queue
I did a run through of the first area to make sure it didn't break.
gif
=> Queue Bug Fix, Artifact QOL, Various Refactoring and Commenting in SGrid and UIArtifact

Slider/Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset, Slider/Assets/Prefabs/UI/UICanvas.prefab, Slider/Assets/Scripts/Discord/DiscordController.cs, Slider/Assets/Scripts/Sliders/Grid/SGrid.cs
Removed extraneous UIManager components from various UI game objects to avoid issues with singleton. Updated Discord Rich Presence to use OnTileCollected and OnSceneChanged events rather than just updating the status every 5s.
Discord Rich Presence
Loaded Village, Caves and Desert and checked that Rich Presence and UI worked correctly. Also loaded MainMenu and transitioned to Village, seeing that Rich Presence worked correctly.
=> Discord Rich Presence Improvements + UIManager Issue Fix

Slider/Assets/EventSystemManager.cs, Slider/Assets/EventSystemManager.cs.meta, Slider/Assets/Scripts/UI/Helper/UIClick.cs, Slider/Assets/TavernkeeperBuyMenuManager.cs, Slider/Assets/TavernkeeperBuyMenuManager.cs.meta
- PlayerAction no longer selects buttons in the artifact menu (specifically in the Ocean area.) 
- Buying a slider in the buy menu of the Tavernkeeper UI now selects the uppermost buy button. The same is true when re-entering the menu after buying a slider.
[Make arrow keys/WASD work in tavernkeeper ui](https://trello.com/c/9oOtL6Ao)
It works, please trust me.
=> Make PlayerAction No Longer Trigger Artifact Buttons, Fix Buy Menu Issue

Slider/Assets/Scripts/Audio/AudioManager.cs, Slider/Assets/Scripts/Discord/DiscordController.cs, Slider/Assets/Scripts/Map/Mountain/Meltable.cs, Slider/Assets/Scripts/Map/Puzzles/ChadRace.cs, Slider/Assets/Scripts/Misc/Singleton.cs, Slider/Assets/Scripts/Sliders/Grid/AreaGrids/DesertGrid.cs, Slider/Assets/Scripts/UI/Artifact/AreaArtifacts/Mountain/MountainUITrackerManager.cs, Slider/Assets/Scripts/UI/UINavigationManager.cs
Singleton now supports "if instance is already set then destroy the one trying to take over right now"
This also suppresses some warnings that were driving me slowly insane.
N/A
Moved between Main Menu, Cutscene, and Village and confirmed that audio still worked properly
=> Update Singleton, Suppress Some Warnings

Slider/Assets/Scripts/UI/Artifact/AreaArtifacts/OceanArtifact.cs, Slider/Assets/Scripts/UI/Artifact/UIArtifact.cs
which solved the weird bug which occured when automove was active and the player tried dragging the tile instead of clicking
I added an additional bool argument to SelectButton  which allows it to know when it was called inside the 2 dragging methods and disables automove if so.
one of the bug ones ig
enabled automove and tried dragging and nothing weird happend (streamed it to daniel)
=> fixed tile dragging and auto move interaction bug

Slider/Assets/Materials/CustomTextShader.shader, Slider/Assets/Materials/CustomTextShader.shader.meta, Slider/Assets/Materials/SpriteWhite.mat, Slider/Assets/Prefabs/Player/Player.prefab
-Added a black camera which renders behind everything to the player prefab. This prevents seeing UI tearing when using non 16:9 aspect ratios
-Made custom text shader with a bunch of properties so unity won't yell at us
=> Fix UI tearing on non 16:9 w/ black camera and White Stencil Error

Slider/Assets/Scripts/UI/Artifact/UIArtifact.cs
changed some stuff in ui artifact to make tiles execute faster as u queue more of them
added a counter that increases whenever a move is executed that then affects the duration property of the next smove and animation duration = move duration * base duration. also when you try dragging with automove, it automoves if the thing ur cursor is hovering is the same stile. if u dont hover over an stile then the highlighting goes away
Also apparently raycast targets mess this up so i removed that 💀
=> improved fast moving and drag and drop behavior

Slider/Assets/Prefabs/UI/OptionsPanel.prefab, Slider/Assets/Prefabs/UI/OptionsPanel.prefab.meta, Slider/Assets/Prefabs/UI/UICanvas.prefab, Slider/Assets/Scenes/MainMenu.unity, Slider/Assets/Scripts/Steamworks.NET/AchievementManager.cs
Fixes an issue where AchievementManager would throw an error and prevent transitioning between scenes if it was not present in the scene or if some other issue occurred when getting achievement data.
Additionally, this PR includes a refactoring of the Options Menu to use a shared prefab for Main Menu and in-game.
[Refactor Options menu so it can be used in-game and in main menu](https://trello.com/c/elawqME0)
Started in Village, moved to Ocean, then moved back to Village
=> Fix AchievementManager Error on Scene Change, Refactor Options Menu to Use a Prefab

Slider/Assets/Scripts/Steamworks.NET/AchievementManager.cs
Fixes softlocks occurring when starting from a scene other than the Main Menu (since there is no SteamManager object in other scenes) or when not connected to Steam.
=> Fix AchievementManager errors when Steam is not connected or instance is null

Slider/Assets/Misc/Input/Controls.cs, Slider/Assets/Scripts/Effects/CameraDolly.cs
Adds BindingHeldBehaviors to Controls which allow for triggering a callback when a control is held for a certain amount of time. Used this new functionality to allow skipping the Village intro camera dolly by holding down the Player.Action control for a short time.
None?
Held down button during intro dolly and observed that dolly was skipped. Tapped button and observed that dolly was not skipped. Tapped, released, then held button and observed that it was still not skipped.
=> Add BindingHeldBehavior to Controls and use it for Village camera dolly skip

Slider/Assets/Scripts/NPCs/NPCDialogueContext.cs, Slider/Assets/Scripts/Player/IInteractable.cs, Slider/Assets/Scripts/Player/IInteractable.cs.meta, Slider/Assets/Scripts/Player/PlayerAction.cs, Slider/Assets/Scripts/Utility/Control/PlayerConditionals.cs
Updates interaction code to have PlayerAction track a list of available interactables and interact with all of them that are tied for highest priority when the interact button is pressed. Also establishes a priority for interacting and item picking up/dropping:
**Picking Up Item = Interacting > Dropping**
This means that you can pick up an item and interact (e.g. talk to an NPC) at the same time with one button press but will not drop an item if you interact with something.
As a side effect, we also now have the . . . prompt for talking to NPCs when there is more dialogue to show.
[Make it so pressing "Action" prioritizes actions over throwing item](https://trello.com/c/fT1rYnXk)
Picked up the Anchor and tried talking to NPCs, going through doors, etc. Also tried holding an Anchor and …
=> Update interactions to be prioritized over dropping items

Slider/Assets/Scripts/Map/Ocean/NPCRotation.cs, Slider/Assets/Scripts/Sliders/Grid/AreaGrids/OceanGrid.cs, Slider/Assets/Scripts/UI/OceanShop/TavernPassManager.cs
biggest things are: bob now gives out tile 5 instead of tile 4. this means the player has to complete fezzewig to unlock all the other tiles. 
Other thing is now mako has different dialogue thats more relevant and hints the player about using the anchor as well as suggesting that bob may know a thing or two
=> Ocean polish: making anchor easier to figure out for the player

Slider/Assets/Scripts/NPCs/NPCDialogueContext.cs
Removes extraneous code that would remove an NPC from the player's interactable list when waitUntilPlayerAction was false. This caused issues and is no longer needed anyway due to changes since the initial refactoring of player interaction.
Boomo's summons
=> Fix issues with NPC interaction when waitUntilPlayerAction is false

Slider/Assets/Scripts/AI/Behaviour Trees/CustomNodes/SetDestToAvoidPlayerNode.cs, Slider/Assets/Scripts/AI/Behaviour Trees/CustomNodes/SetDestToNearestValidPtNode.cs, Slider/Assets/Scripts/AI/Pathfinding/WorldNavigation.cs, Slider/Assets/Scripts/AI/Rat/RatAI.cs, Slider/Assets/Scripts/Map/PaintedCostMap.cs
- Made some adjustments to the costmap
- Commented out code that unparented the rat from tiles since we don't do that anymore anyway.
- Removed cost map generation since it happens every frame anyway and we already have the costmap (might want to add back. Idk which is actually faster).
- Switched the order of behaviour nodes so that it moves to the nearest valid tile first before avoiding the player (fixes stalling issues I think, it didn't break the movement when I tested it).
- Changed stile getter in PaintedCostMap.cs to handle moves (linear search, but it's honestly not much slower). 
idk
idk
I'm too lazy and gdc is tomo.
=> Rat Hot Fixes Before GDC

Slider/Assets/Scripts/Map/Puzzles/ChadRace.cs
Player-winning text prompt rendered using `DisplayAndTriggerDialogue()` function in `ChadRace.cs` rather than in Unity Editor
chad race cheating player feedback systems so you know if youre racing or not
- Navigate to Assets/Scenes/Dev/Avery/ and start the Jungle Scene
- Race Chad and win, observe the bug as Chad approaches
=> Changes Player Winning text prompt to rely on jungleChadSpeak var instead of typing the text in Unity Editor

Slider/Assets/Scripts/Sliders/Grid/AreaSTiles/MirageSTileManager.cs, Slider/Assets/Scripts/Sliders/Grid/SGridAnimator.cs, Slider/Assets/Scripts/UI/Artifact/AreaArtifacts/DesertArtifact.cs, Slider/Assets/Scripts/UI/Artifact/Plugins/ArtifactTBPluginMirage.cs
- Clicking the mirage tiles in the UI doesn't do anything anymore.
- Moving onto mirage tile is one click
- When player is on mirage tile and it gets disabled, they get pushed back to the same location on the real tile with blackout/sound effect.
- The mirage tile appears on move complete instead of immediately. I think it might look better if it faded into existence. It looked like Travis was working on something like this?
https://trello.com/c/CnMtA7vh/445-desert-mirage
- I tested that it worked with queueing a bunch of moves and different mirage tiles/smove combinations
- Fixed issue with player reparenting.
- There's another issue with dialogue boxes not disappearing on mirage tiles, but I think that's a separate issue.
=> Mirage Tile Fixes

Slider/Assets/Scripts/Map/MagiTech/GemManager.cs, Slider/Assets/Scripts/Map/MagiTech/MagiGem.cs
Added EnableGem function to allow NPCs to only enable if the player doesn't already have the gem.
Gems enabled by default are managed by MagiTech grid
Added dialogue options for Curator, Burger Guy, and VIP brother when the player has the gem (and the slider if the npc gives one)
I grab gem, I load another scene, I come back
=> Gem Serialization

Slider/Assets/Scripts/Map/Interactable/Items/DesyncItem.cs, Slider/Assets/Scripts/Map/Interactable/Items/Item.cs, Slider/Assets/Scripts/Map/MagiTech/DesyncLever.cs, Slider/Assets/Scripts/Map/MagiTech/GemManager.cs, Slider/Assets/Scripts/Map/MagiTech/MagiGem.cs, Slider/Assets/Scripts/Map/MagiTech/MagiLaser.cs, Slider/Assets/Scripts/Sliders/Grid/AreaGrids/MagiTechGrid.cs, Slider/Assets/Scripts/UI/Artifact/Plugins/ArtifactTBPluginLaser.cs, Slider/Assets/Scripts/UI/Artifact/UIArtifact.cs, Slider/Assets/Sprites/Items/breadge.png.meta
-Desync items and lever count anchored tile of desync as desync
-anchored tile of desync store in magitech grid
-fixed oil serialization 
-fixed gem serialization
-fixed burger reflections
-fixed issue where you could enable gfuel without all gems
-fixed laser not rendering when hitting rocket
-fixed some laser render order issues
-fixed bug where attempting to put gem into machine caused NRE if sprites not loaded
https://trello.com/c/Z3NicWDb/561-me-when-more-magitech-bugs
looked at it
=> Fix some magitech bugs

Slider/Assets/Scripts/NPCs/NPCDialogueContext.cs
That was easy.
NPCs show pings for any unread dialogue. Pings don't reappear when dconds revert, unless there was unread dialogue.  Pings re-appear when walking away from an npc if there is unread dialogue.
=> Better NPC Pings
